"""empty message

Revision ID: 3cc4948b5fbe
Revises: d38d7917eb00
Create Date: 2024-10-09 13:10:35.023898

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3cc4948b5fbe'
down_revision = 'd38d7917eb00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.add_column(sa.Column('buy_orders', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('sell_orders', sa.Float(), nullable=True))
        batch_op.drop_column('in_orders')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.add_column(sa.Column('in_orders', mysql.FLOAT(), nullable=True))
        batch_op.drop_column('sell_orders')
        batch_op.drop_column('buy_orders')

    # ### end Alembic commands ###
