"""update OtherTransaction and OtherBody tabs

Revision ID: 3fc5fbccf251
Revises: a74ba779fda2
Create Date: 2023-12-28 07:19:25.961453

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3fc5fbccf251'
down_revision = 'a74ba779fda2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('alert', schema=None) as batch_op:
    #     batch_op.create_foreign_key(None, 'ticker', ['price_ticker_id'], ['id'])
    #     batch_op.create_foreign_key(None, 'watchlist_asset', ['watchlist_asset_id'], ['id'])

    with op.batch_alter_table('other_body', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount_usd', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('cost_now_usd', sa.Float(), nullable=True))
        # batch_op.create_foreign_key(None, 'ticker', ['amount_ticker_id'], ['id'])
        # batch_op.create_foreign_key(None, 'ticker', ['cost_now_ticker_id'], ['id'])
        batch_op.drop_column('cost_now_with_ticker')
        batch_op.drop_column('amount_with_ticker')

    with op.batch_alter_table('other_transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount_usd', sa.Float(), nullable=True))
        # batch_op.create_foreign_key(None, 'ticker', ['amount_ticker_id'], ['id'])
        batch_op.drop_column('amount_with_ticker')

    # with op.batch_alter_table('user', schema=None) as batch_op:
    #     batch_op.create_foreign_key(None, 'ticker', ['currency_ticker_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('other_transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount_with_ticker', mysql.FLOAT(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('amount_usd')

    with op.batch_alter_table('other_body', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount_with_ticker', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('cost_now_with_ticker', mysql.FLOAT(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('cost_now_usd')
        batch_op.drop_column('amount_usd')

    with op.batch_alter_table('alert', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
