"""add price in Ticker

Revision ID: 6ed13bcc0de4
Revises: 3fc5fbccf251
Create Date: 2024-01-09 17:26:22.081384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ed13bcc0de4'
down_revision = '3fc5fbccf251'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('alert', schema=None) as batch_op:
    #     batch_op.create_foreign_key(None, 'watchlist_asset', ['watchlist_asset_id'], ['id'])
    #     batch_op.create_foreign_key(None, 'ticker', ['price_ticker_id'], ['id'])
    #
    # with op.batch_alter_table('other_body', schema=None) as batch_op:
    #     batch_op.create_foreign_key(None, 'ticker', ['amount_ticker_id'], ['id'])
    #     batch_op.create_foreign_key(None, 'ticker', ['cost_now_ticker_id'], ['id'])
    #
    # with op.batch_alter_table('other_transaction', schema=None) as batch_op:
    #     batch_op.create_foreign_key(None, 'ticker', ['amount_ticker_id'], ['id'])

    with op.batch_alter_table('ticker', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Float(), nullable=True))

    # with op.batch_alter_table('user', schema=None) as batch_op:
    #     batch_op.create_foreign_key(None, 'ticker', ['currency_ticker_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('ticker', schema=None) as batch_op:
        batch_op.drop_column('price')

    with op.batch_alter_table('other_transaction', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('other_body', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('alert', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
