"""add other_body.cost_now_with_ticker

Revision ID: a74ba779fda2
Revises: 180d7fff0551
Create Date: 2023-12-27 12:53:07.438152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a74ba779fda2'
down_revision = '180d7fff0551'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('alert', schema=None) as batch_op:
    #     batch_op.create_foreign_key(None, 'ticker', ['price_ticker_id'], ['id'])
    #     batch_op.create_foreign_key(None, 'watchlist_asset', ['watchlist_asset_id'], ['id'])

    with op.batch_alter_table('other_body', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cost_now_with_ticker', sa.Float(), nullable=True))
        # batch_op.create_foreign_key(None, 'ticker', ['cost_now_ticker_id'], ['id'])
        # batch_op.create_foreign_key(None, 'ticker', ['amount_ticker_id'], ['id'])

    # with op.batch_alter_table('other_transaction', schema=None) as batch_op:
    #     batch_op.create_foreign_key(None, 'ticker', ['amount_ticker_id'], ['id'])
    #
    # with op.batch_alter_table('user', schema=None) as batch_op:
    #     batch_op.create_foreign_key(None, 'ticker', ['currency_ticker_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('other_transaction', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('other_body', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('cost_now_with_ticker')

    with op.batch_alter_table('alert', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
