"""empty message

Revision ID: d38d7917eb00
Revises: ec16f587e155
Create Date: 2024-10-09 13:08:27.214075

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd38d7917eb00'
# down_revision = 'ec16f587e155'
down_revision = '7fade8654c8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset', schema=None) as batch_op:
        # batch_op.drop_constraint('asset_ibfk_3', type_='foreignkey')
        # batch_op.drop_column('wallet_id')
        pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wallet_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('asset_ibfk_3', 'wallet', ['wallet_id'], ['id'])

    # ### end Alembic commands ###
