"""Transaction

Revision ID: f78299b36304
Revises: 
Create Date: 2023-10-05 08:08:12.403014

"""
from alembic import op
import sqlalchemy as sa

from portfolio_tracker.models import Asset


# revision identifiers, used by Alembic.
revision = 'f78299b36304'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('base_asset_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('quote_asset_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('quote_ticker_id', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('base_quantity', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('quote_quantity', sa.Float(), nullable=True))
        batch_op.alter_column('date',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.Date(),
               existing_nullable=True)
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=24),
               type_=sa.String(length=2),
               existing_nullable=True)
        batch_op.drop_constraint('asset_id', type_='foreignkey')
        batch_op.drop_constraint('wallet_asset_id', type_='foreignkey')
        batch_op.drop_constraint('against_ticker_id', type_='foreignkey')
        batch_op.create_foreign_key('quote_asset_id', 'wallet_asset', ['quote_asset_id'], ['id'])
        batch_op.create_foreign_key('quote_ticker_id', 'ticker', ['quote_ticker_id'], ['id'])
        batch_op.create_foreign_key('base_asset_id', 'asset', ['base_asset_id'], ['id'])
        batch_op.drop_column('asset_id')
        batch_op.drop_column('wallet_id')
        batch_op.drop_column('against_ticker_id')
        batch_op.drop_column('quantity')
        batch_op.drop_column('amount')
        batch_op.drop_column('wallet_asset_id')

    with op.batch_alter_table('wallet', schema=None) as batch_op:
        batch_op.drop_column('money_all')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wallet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('money_all', sa.FLOAT(), nullable=True))

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wallet_asset_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('amount', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('quantity', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('against_ticker_id', sa.VARCHAR(length=32), nullable=True))
        batch_op.add_column(sa.Column('wallet_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('asset_id', sa.INTEGER(), nullable=True))
        # batch_op.drop_constraint(None, type_='foreignkey')
        # batch_op.drop_constraint(None, type_='foreignkey')
        # batch_op.drop_constraint(None, type_='foreignkey')
        # batch_op.create_foreign_key(None, 'asset', ['asset_id'], ['id'])
        # batch_op.create_foreign_key(None, 'wallet', ['wallet_id'], ['id'])
        # batch_op.create_foreign_key(None, 'wallet_asset', ['wallet_asset_id'], ['id'])
        batch_op.alter_column('type',
               existing_type=sa.String(length=2),
               type_=sa.VARCHAR(length=24),
               existing_nullable=True)
        batch_op.alter_column('date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(length=32),
               existing_nullable=True)
        batch_op.drop_column('quote_quantity')
        batch_op.drop_column('base_quantity')
        batch_op.drop_column('quote_ticker_id')
        batch_op.drop_column('quote_asset_id')
        batch_op.drop_column('base_asset_id')

    # ### end Alembic commands ###
