"""last visit

Revision ID: fc14bb66dd6d
Revises: 
Create Date: 2023-10-23 17:00:02.220692

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fc14bb66dd6d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('alert', schema=None) as batch_op:
    #     batch_op.create_foreign_key(None, 'ticker', ['price_ticker_id'], ['id'])
    #     batch_op.create_foreign_key(None, 'watchlist_asset', ['watchlist_asset_id'], ['id'])

    # with op.batch_alter_table('other_body', schema=None) as batch_op:
    #     batch_op.create_foreign_key(None, 'ticker', ['amount_ticker_id'], ['id'])

    # with op.batch_alter_table('other_transaction', schema=None) as batch_op:
    #     batch_op.create_foreign_key(None, 'ticker', ['amount_ticker_id'], ['id'])

    # with op.batch_alter_table('user', schema=None) as batch_op:
    #     batch_op.create_foreign_key(None, 'ticker', ['currency_ticker_id'], ['id'])

    with op.batch_alter_table('user_info', schema=None) as batch_op:
        batch_op.alter_column('last_visit',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.DateTime(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_info', schema=None) as batch_op:
        batch_op.alter_column('last_visit',
               existing_type=sa.DateTime(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('other_transaction', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('other_body', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('alert', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
