name: Python CI/CD

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Set up virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python -m unittest discover

  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install nmap
        run: sudo apt-get install -y nmap

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          eval "$(ssh-agent -s)"
          echo "${{ secrets.SSH_KEY_PASSPHRASE }}" | ssh-add ~/.ssh/id_rsa

      - name: Resolve SSH host
        run: |
          nslookup ${{ secrets.SSH_HOST }}

      # - name: Ping SSH host
      #   run: |
      #     ping -c 4 ${{ secrets.SSH_HOST }}
      #
      #

      - name: Write SSH keys
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          host='allmyportfolios.com'
          hosts="$(dig +short "$host" | grep -v '\.$' | sed -z 's|\n|,|g')$host"
          ssh-keyscan -H "$hosts" > ~/.ssh/known_hosts

      - name: Print SSH host keys
        run: |
          echo "Trying to get SSH host keys for ${{ secrets.SSH_HOST }}..."
          KEYS=$(ssh-keyscan -H -t ed25519 -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_HOST }} 2>&1)
          echo "Command output:"
          echo "$KEYS"

      - name: Add SSH host to known hosts
        run: | 
          ssh-keyscan -H -t ed25519 -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
          # ssh-keyscan -t ed25519 allmyportfolios.com >> ~/.ssh/known_hosts
          # ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to server
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
          SSH_PORTS: ${{ secrets.SSH_PORTS }}
          SSH_PRIVATE_KEY: ~/.ssh/id_rsa
        run: |
          ./deploy.sh

      - name: Notify success
        if: success()
        run: |
          echo "Деплой успешно завершен!"

      - name: Notify failure
        if: failure()
        run: |
          echo "Деплой завершился с ошибкой!"
